---
# defaults file for common

custom_apt_repos:
  - ppa:snwh/ppa
  - ppa:nathan-renniewaldock/flux

custom_remove_apt_packages:
  - lightdm

custom_apt_packages:
  # desktop
  - gnome-shell
  - gdm3
  - gnome-tweak-tool
  - paper-icon-theme
  - fluxgui
  - kubuntu-desktop
  - latte-dock

  # tools
  - tilix

custom_deb_packages: []
