---

- hosts: localhost
  tasks:
    - name: Install common packages
      include_role:
        name: common

    - name: Install Java
      include_role:
        name: java

    - name: Install Bazel
      include_role:
        name: bazel

    - name: Install Docker
      include_role:
        name: docker

    - name: Install PyCharm
      include_role:
        name: pycharm

    - name: Install IntelliJ IDEA
      include_role:
        name: intellij

    - name: Set editor settings
      lineinfile:
        path: "{{ item.path }}"
        line: "{{ item.line }}"
        create: yes
        backup: yes
      with_items:
        - { path: '~/.bashrc', line: 'export EDITOR=nano' }
        - { path: '~/.nanorc', line: 'set tabsize 4' }
        - { path: '~/.nanorc', line: 'set tabstospaces' }

    - name: Set favorite apps
      shell: >
        dconf write /org/gnome/shell/favorite-apps
        "[
            'google-chrome.desktop',
            'firefox.desktop',
            'com.gexperts.Tilix.desktop',
            'org.gnome.Nautilus.desktop',
            'slack.desktop',
            'jetbrains-pycharm-ce.desktop',
            'jetbrains-idea-ce.desktop'
         ]"
