---
# defaults file for common
common_apt_keys:
  - keyserver: keyserver.ubuntu.com
    id: 23F3D4EA75716059  # github cli

common_apt_repos:
  - "deb [arch=amd64] https://cli.github.com/packages stable main"

common_apt_packages:
  # system
  #- python-dev (deprecated)
  - python3.7-dev
  #- gir1.2-gtop-2.0
  #- gir1.2-networkmanager-1.0
  #- gir1.2-clutter-1.0
  - openjdk-8-jdk
  - maven
  - libatlas3-base
  - libpq-dev
  - libsasl2-dev

  # tools
  - silversearcher-ag
  - curl
  - htop
  - iotop
  - iftop
  - zsh
  - rdesktop
  - gh  # github cli
  - ncdu
  - cloc

common_pip_packages:
  - psutil
  - virtualenvwrapper

common_chrome_download_url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"

common_deb_packages:
  - "{{ common_chrome_download_url }}"
