---
# defaults file for common
common_apt_keys:
  - keyserver: keyserver.ubuntu.com
    id: C99B11DEB97541F0  # github cli

common_apt_repos:
  - https://cli.github.com/packages

common_apt_packages:
  # system
  - python-dev
  - python3.7-dev
  - gir1.2-gtop-2.0
  - gir1.2-networkmanager-1.0
  - gir1.2-clutter-1.0
  - openjdk-8-jdk
  - maven
  - libatlas3-base
  - libpq-dev
  - libsasl-dev

  # tools
  - silversearcher-ag
  - curl
  - htop
  - iotop
  - iftop
  - zsh
  - redesktop
  - gh  # github cli

common_pip_packages:
  - psutil
  - virtualenvwrapper

common_slack_version: 3.2.1
common_slack_download_url: "https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ common_slack_version }}-amd64.deb"

common_chrome_download_url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"

common_deb_packages:
  - "{{ common_slack_download_url }}"
  - "{{ common_chrome_download_url }}"
