---
# tasks file for bazel

- name: Install Bazel dependencies
  apt:
    name: "{{ bazel_apt_dependencies }}"
  become: yes

- name: Download Bazel
  get_url:
    url: "{{ bazel_download_url }}"
    dest: "~/Downloads/{{ bazel_install_script }}"
    mode: 0755

- name: Install Bazel
  shell: "~/Downloads/{{ bazel_install_script }} --user"

- name: Add bash completion script to bashrc
  lineinfile:
    path: "~/.bashrc"
    line: "{{ item }}"
  with_items:
    - "source ~/.bazel/bin/bazel-complete.bash"
    - 'export PATH="$PATH:$HOME/.bazel/bin"'
