---
# tasks file for bazel

- name: Install Bazel dependencies
  apt:
    name: "{{ bazel_apt_dependencies }}"
  become: yes

- name: Add ubuntu toolchain test repo
  apt_repository:
    repo: 'ppa:ubuntu-toolchain-r/test'
  become: yes

- name: Install bazelisk
  get_url:
    url: "{{ bazelisk_download_url }}"
    checksum: sha256:98af93c6781156ff3dd36fa06ba6b6c0a529595abb02c569c99763203f3964cc
    dest: ~/bin/bazel
    mode: 0755

- name: Add bash completion script to bashrc
  lineinfile:
    path: "~/.bashrc"
    line: "{{ item }}"
  with_items:
    - "source ~/.bazel/bin/bazel-complete.bash"
    - 'export PATH="$PATH:$HOME/.bazel/bin"'
