---
# tasks file for common

- name: Add apt repositories
  apt_repository:
    repo: "{{ item }}"
  become: yes
  with_items: "{{ custom_apt_repos }}"

- name: Remove unwanted apt packages
  apt:
    name: "{{ custom_remove_apt_packages }}"
    purge: yes
    state: absent
  become: yes

- name: Install apt packages
  apt:
    name: "{{ custom_apt_packages }}"
  become: yes

- name: Install deb packages
  apt:
    deb: "{{ item }}"
  become: yes
  with_items: "{{ custom_deb_packages }}"

- name: Make tilix the default terminal
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/tilix
    priority: 30
  become: yes

# move window controls to the right side (default is 'close,minimize,maximize:')
#- name: Move window controls to the right side
#  shell: "gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'"

- name: Set gitconfig
  copy:
    src: gitconfig
    dest: "~/.gitconfig"
    mode: 0664

- name: Set ssh config
  copy:
    src: ssh_config
    dest: "~/.ssh/config"
    mode: 0664

- name: Add custom Xmodmap
  copy:
    src: Xmodmap
    dest: "~/.Xmodmap"
    mode: 0664

- name: Set Xmodmap
  shell: "xmodmap ~/.Xmodmap"

- name: Setup swap file
  command: "dd if=/dev/zero of={{ custom_swap_file_path }} bs=1024 count={{ ansible_memtotal_mb }}"
  args:
    creates: "{{ custom_swap_file_path }}"
  become: yes

- name: Set swap file permissions
  file:
    path: "{{ custom_swap_file_path }}"
    owner: root
    group: root
    mode: 0600
  become: yes

- name: Format swap file
  command: "mkswap {{ custom_swap_file_path }}"
  become: yes

- name: Add swap file to the system
  command: "swapon {{ custom_swap_file_path }}"
  become: yes

- name: Add swap mount to fstab
  mount:
    path: "{{ custom_swap_file_path }}"
    fstype: swap
    opts: sw
    passno: 0
    dump: 0
    state: present
  become: yes
