---
# defaults file for bazel

bazelisk_download_url: https://github.com/bazelbuild/bazelisk/releases/download/v1.3.0/bazelisk-linux-amd64
bazel_apt_dependencies:
  - pkg-config
  - zip
  - g++
  - zlib1g-dev
  - unzip
