---
# tasks file for common
- name: Add apt keys
  apt_key:
    keyserver: "{{ item.keyserver }}"
    id: "{{ item.id }}"
  become: yes
  with_items: "{{ common_apt_keys }}"

- name: Add apt repositories
  apt_repository:
    repo: "{{ item }}"
  become: yes
  with_items: "{{ common_apt_repos }}"

- name: Install apt packages
  apt:
    name: "{{ common_apt_packages }}"
  become: yes

- name: Install deb packages
  apt:
    deb: "{{ item }}"
  become: yes
  with_items: "{{ common_deb_packages }}"

- name: Install pip packages
  pip:
    name: "{{ item }}"
    extra_args: --user
  with_items: "{{ common_pip_packages }}"

- name: Add pip config directory
  file:
    path: "~/.config/pip"
    state: directory

- name: Set pip config
  copy:
    src: pip.conf
    dest: "~/.config/pip/pip.conf"
    mode: 0664

- name: Add virtualenvwrapper settings to bashrc
  lineinfile:
    path: "~/.bashrc"
    line: "{{ item }}"
  with_items:
    - "export WORKON_HOME=$HOME/.virtualenvs"
    - "export PROJECT_HOME=$HOME/Projects"
    - "source ~/.local/bin/virtualenvwrapper.sh"

- name: Download fuzzy finder
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "~/.fzf"
    depth: 1

- name: Install fuzzy finder
  shell: "~/.fzf/install --all"
